name: Build and Push to ACR
on:
  workflow_dispatch:
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: actions/checkout@v2
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push to ACR
        uses: actions/checkout@v2
        with:
          push: true
          tags: sample:${{ github.sha }}
          file: Dockerfile
